export const SIGNIN_API = "SIGNIN_API"
export const REDIRECT_SAGA ='REDIRECT_SAGA'

//-------------------------Login---------------
export const USLOGIN_ACTION ='USLOGIN_ACTION'

//-------------------------GetUserCategoty
export const GET_CATEGORY = 'GET_CATEGORY'
export const FETCH_DATA_CATEGORY = 'FETCH_DATA_CATEGORY'

export const ADD_PROJECT='ADD_PROJECT'
//-------------------TAB PROJECT MANAGEMENT
export const FECTH_PROJECT_MANAGEMENT='FECTH_PROJECT_MANAGEMENT'
export const FECTH_PROJECT_MANAGEMENT_NORMAL='FECTH_PROJECT_MANAGEMENT_NORMAL'

export const  SEND_UPDATE_SAGA='SEND_UPDATE_SAGA'
export const  SEND_UPDATE_SAGA_NORMAL='SEND_UPDATE_SAGA_NORMAL'

export const  DELETE_PROJECT_SAGA='DELETE_PROJECT_SAGA'

export const SEARCH_AUTO_COMPLETE_SAGA = 'SEARCH_AUTO_COMPLETE'
export const SEARCH_AUTO_COMPLETE_NORMAL = 'SEARCH_AUTO_COMPLETE_nORMAL'

export const ASSIGN_MEMBER_SAGA= 'ASSIGN_MEMBER_SAGA'
export const CHANGE_MAIN_ZONE_SAGA= 'CHANGE_MAIN_ZONE_SAGA'
export const CHANGE_MAIN_ZONE_SAGA_NORMAL= 'CHANGE_MAIN_ZONE_SAGA_NORMAL'


export const GET_ALL_PROJECT_FOR_MODAL_SAGA= 'GET_ALL_PROJECT_FOR_MODAL_SAGA'
export const GET_ALL_PROJECT_MODAL_NORMAL= 'GET_ALL_PROJECT_MODAL_NORMAL'

export const GET_ALL_TASK_TYPE_SAGA= 'GET_ALL_TASK_TYPE_SAGA'
export const GET_TASK_TYPE_NORMAL= 'GET_TASK_TYPE_NORMAL'

export const GET_ALL_TASK_PRIORITY_SAGA= 'GET_ALL_TASK_PRIORITY_SAGA'
export const GET_ALL_TASK_PRIORITY_NORMAL= 'GET_ALL_TASK_PRIORITY_NORMAL'

export const GET_ALL_USER_MODAL_SAGA= 'GET_ALL_USER_MODAL_SAGA'
export const GET_ALL_USER_MODAL_NORMAL= 'GET_ALL_USER_MODAL_NORMAL'
